---
name: neuralworks

channels:
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - setuptools
  - wheel
  # requirements-dev.txt
  - autopep8>=2.0.1
  - cohesion>=1.0.0
  - coverage>=7.0.0
  - darglint>=1.8.1
  - docformatter>=1.5.0
  - flake8-bugbear>=22.12.6
  - flake8-comprehensions>=3.10.1
  - flake8-docstrings>=1.6.0
  - flake8-logging-format>=0.9.0
  - flake8-polyfill>=1.0.2
  - flake8-print>=5.0.0
  - flake8-pytest-style>=1.6.0
  - flake8-simplify>=0.19.3
  - flake8-use-pathlib>=0.3.0
  - flake8>=6.0.0
  - isort[colors,requirements_deprecated_finder,pipfile_deprecated_finder]>=5.11.4
  - mccabe>=0.7.0
  - mypy>=0.991
  - pep8-naming>=0.13.2
  - pep8>=1.7.1
  - pluggy>=1.0.0
  - pre-commit>=2.20.0
  - psutil>=5.9.4
  - pycodestyle>=2.10.0
  - pydocstyle>=6.1.1
  - pyflakes>=3.0.1
  - pylint>=2.15.9
  - pytest-cov>=4.0.0
  - pytest-datadir>=1.4.1
  - pytest-testinfra>=7.0.0
  - pytest-xdist>=3.1.0
  - pytest>=7.2.0
  - pyupgrade>=3.3.1
  - radon>=5.1.0
  - toml>=0.10.2
  - tryceratops>=1.1.0
  - types-PyYAML>=6.0.12.2
  - types-requests>=2.28.11.5
  - types-setuptools>=65.6.0.2
  - unittest2pytest>=0.4
  - yapf>=0.32.0

  - pip:
      # requirements-dev.txt
      - autoflake>=2.0.0
      - bandit>=1.7.4
      - cleanpy>=0.3.1
      - fixit>=0.1.4
      - flake8_implicit_str_concat>=0.3.0
      - flake8-bandit>=4.1.1
      - flake8-commas>=2.1.0
      - flake8-copyright>=0.2.3
      - flake8-debugger>=4.1.2
      - flake8-executable>=2.1.2
      - flake8-no-pep420>=2.3.0
      - flake8-quotes>=3.3.2
      - flake8-type-checking>=2.3.0
      - flake8-typing-imports>=1.14.0
      - mypy-extensions>=0.4.3
      - pyclean>=2.2.0
      - pre-commit>=2.21.0
