---
name: neuralworks

channels:
  - conda-forge

dependencies:
  - python=3.8

  - pip
  - setuptools
  - wheel

  # requirements.txt

  # Base
  - ipython>=5.5.0
  # required by pycaret.internal.display
  - ipywidgets>=7.6.5
  # required by pycaret.internal.display
  - tqdm>=4.62.0
  # Can't >=1.23 because of sktime/numba
  - numpy>=1.21,<1.23
  # Can't >=1.6 because of sktime
  - pandas>=1.3.0,<1.6.0
    # Required by pycaret.internal.utils --> pandas.io.formats.style
  - jinja2>=1.2
    # Can't >=2.0.0 due to sktime
  - scipy<2.0.0
  # joblib<1.2.0 is vulnerable to Arbitrary Code Execution (https://github.com/advisories/GHSA-6hrg-qmvc-2xh8)
  - joblib>=1.2.0
  - scikit-learn>=1.0
  - pyod>=0.9.8
  - imbalanced-learn>=0.8.1
  # - category-encoders>=2.4.0
  - lightgbm>=3.0.0
  - numba>=0.55.0
    # Required by pycaret.datasets
  - requests>=2.27.1
  - psutil>=5.9.0
    # Fixes Google Colab issue
  - markupsafe>=2.0.1
  - nbformat>=4.2.0
  - cloudpickle
  - deprecation>=2.1.0
  - importlib_metadata>=4.12.0

  # Plotting
  - matplotlib>=3.3.0
  - scikit-plot>=0.3.7
  - yellowbrick>=1.4
  - plotly>=5.0.0
  # - kaleido>=0.2.1
  - schemdraw>=0.14
  - plotly-resampler>=0.7.2.2

  # Time-series
  - statsmodels>=0.12.1
  # - sktime>=0.14.0,<0.15.0
  - tbats>=1.1.0
    # Matches sktime
  - pmdarima>=1.8.0,!=1.8.1,<3.0.0

  # requirements-optional.txt

  # # Analysis
  - shap>=0.38.0
  # # - interpret>=0.2.7
  - umap-learn>=0.5.2
  # - pandas-profiling>=3.1.0
  - pandas-profiling>=3.5.0
  # For dashboard method
  # - explainerdashboard>=0.3.8
  # For EDA method
  - autoviz>=0.1.36
  # For check_fairness method
  - fairlearn=0.7.0
  # For deep_check method
  - deepchecks>=0.9.2

  # Models
  - xgboost>=1.1.0
  # - catboost>=0.23.2
  - kmodes>=0.11.1
  - mlxtend>=0.19.0
  - statsforecast>=0.5.5
  # not available for M1 macs
  # - scikit-learn-intelex>=2021.6.3
  # scikit-learn-intelex>=2021.6.3; platform_machine == 'x86_64' or platform_machine == 'AMD64'

  # # Tuners
  # - tune-sklearn>=0.2.1 # ; python_version < '3.10' or platform_system != 'Windows'
  # - protobuf<4.0.0; python_version < '3.10' or platform_system != 'Windows' # broken in Ray <1.13
  - protobuf<4.0.0
  # # - ray[tune]>=1.0.0; python_version < '3.10' or platform_system != 'Windows'
  # # - ray-tune>=1.0.0; python_version < '3.10' or platform_system != 'Windows'
  - hyperopt>=0.2.7
  - optuna>=3.0.0
  - scikit-optimize>=0.9.0

  # # MLOps
  - mlflow>=1.24.0,<2.0.0
  # # - gradio>=2.8.10
  # For deploy_model method
  # - boto3>=1.24.56
  # For web api
  - fastapi>=0.75.0
  # For web api
  - uvicorn>=0.17.6
  # For model conversion
  # # - m2cgen>=0.9.0
  # for drift reporting
  - evidently>=0.1.45.dev0

  # # NLP
  # - nltk>=3.7
  # - pyLDAvis>=3.3.1
  # - gensim>=4.1.2
  # - spacy>=3.2.3
  # - wordcloud>=1.8.1
  # # - textblob>=0.17.1

  # # Parallel
  - fugue~=0.6.6
  - flask>=2.0.3

  # requirements-prophet.txt
  # - prophet>=1.0.1

  # RAY
  # https://docs.ray.io/en/latest/ray-overview/installation.html
  - grpcio=1.43.0

  # CUSTOM

  # pandas - efficiency
  - Bottleneck>=1.3.5

  # pandas - computation
  - xarray>=2022.11.0

  # pandas - excel support
  - openpyxl>=3.0.10
  - pyxlsb>=1.0.10
  - xlrd>=2.0.1
  - xlsxwriter>=3.0.3
  - xlwt>=1.3.0

  # Dashboard
  - dash-bootstrap-components[pandas]>=1.2.1

  - pip:
      # requirements.txt

      # Base
      - category-encoders>=2.4.0

      # # Plotting
      - kaleido>=0.2.1

      # Time-series
      - sktime>=0.14.0,<0.15.0

      # requirements-optional.txt

      # # Analysis
      - interpret>=0.2.7
      # For dashboard method
      - explainerdashboard>=0.3.8

      # # Models
      - catboost>=0.23.2
      # not available for M1 macs
      # # - scikit-learn-intelex>=2021.6.3

      # Tuners
      # https://docs.ray.io/en/latest/ray-overview/installation.html
      - tune-sklearn>=0.2.1
      - ray[tune]>=1.0.0

      # # # MLOps
      # # - gradio>=2.8.10
      # For model conversion
      - m2cgen>=0.9.0

      # # # NLP
      # # - textblob>=0.17.1

      # # requirements-prophet.txt
      # - cmdstanpy==0.9.68
      # - pystan==2.19.1.1
      # - prophet>=1.0.1
      - prophet>=1.1.0

      # CUSTOM

      # pandas - efficiency
      - numexpr>=2.8.4

      # DEVELOPMENT
      - autopep8>=2.0.1
      - isort[colors,requirements_deprecated_finder,pipfile_deprecated_finder]>=5.11.2
      - toml>=0.10.2
      - yapf>=0.32.0
      - cleanpy>=0.3.1
      - pyclean>=2.2.0
      # - pandas-profiling[notebook]>=3.5.0

      # - pre-commit>=2.21.0
